[package]
name = "mat_calc_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2.0"
mat = { path = "../" }
mat_calc = { path = "../mat_calc" }
mat_macro = { path = "../mat_macro" }
send_wrapper = "0.6.0"
